### ISSUE TITLE
xml-fmt is not a command (curl http://192.168.99.100:8080/javaee-simple-sample/resources/persons | xml-fmt) 

### ISSUE THREAD

**Issue by gautampriya** [docker/community#43] opened 2016-03-26 19:53 UTC
tomee $ curl http://192.168.99.100:8080/javaee-simple-sample/resources/persons | xml-fmt
-bash: xml-fmt: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   343  100   343    0     0   1321      0 --:--:-- --:--:-- --:--:--  1324
(23) Failed writing body
tomee $ curl http://192.168.99.100:8080/javaee-simple-sample/resources/persons | xml
-bash: xml: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   343  100   343    0     0  38195      0 --:--:-- --:--:-- --:--:-- 42875
(23) Failed writing body

**Comment by LuckyJackAubrey** [comment] 2016-03-26 20:23
where do we find/get this command?

**Comment by gautampriya** [comment] 2016-03-26 20:48
In this example provided in chapter 4, curl http://192.168.99.100:8080/javaee-simple-sample/resources/persons | xml-fmt, the output is being piped to xml-fmt command to pretty print the xml. xml-fmt command does not exist on mac.

**Comment by thaJeztah** [comment] 2016-03-27 19:59
Looks like a duplicate of https://github.com/docker/community/issues/37

**Closed** 2016-04-25 23:56 UTC
